ViewModels/HomeViewModel.cs
using Mhltw.Models;
using System.Reflection.Metadata;

namespace Mhltw.ViewModels
{
    public class HomeViewModel
    {
        public List<Product> Burger { get; set; }

        public List<Product> Pizza { get; set; }

        public List<Product> Chicken { get; set; }

        public List<Product> products { get; set; }
        public PagingInfo pagingInfo { get; set; }
    }
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages => (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage);
    }
}

Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Mhltw.Models;
using Mhltw.Repository;

namespace Mhltw.Areas.Admin.Controllers
{
    [Authorize(Roles =SD.Role_Admin)]
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        public CategoryController(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        public async Task<IActionResult> IndexCategory()
        {
            var categories = await _categoryRepository.GetAllAsync();
            return View(categories);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Category category)
        {
            await _categoryRepository.AddAsync(category);
            return RedirectToAction(nameof(IndexCategory));
        }

        public async Task<IActionResult> Details(int id)
        {
            var category = await _categoryRepository.GetByIdAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var category = await _categoryRepository.GetByIdAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id, Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }
            await _categoryRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            var category = await _categoryRepository.GetByIdAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }
            await _categoryRepository.UpdateAsync(category);
            return RedirectToAction(nameof(IndexCategory));
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Mhltw.Models;
using Mhltw.Repository;
using Microsoft.EntityFrameworkCore;
using Mhltw.ViewModels;

namespace Mhltw.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IProductRepository _productRepository;

        public HomeController(IProductRepository productRepository, ApplicationDbContext context)
        {
            _productRepository = productRepository;
            _context = context;
        }

        public async Task<IActionResult> Index(string name,int page = 1)
        {
            
            int pageSize = 6;
            var prods = await _context.Products.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();
            var chicken = await _context.Products.Where(m => m.CategoryId == 3).ToListAsync();
            var burger = await _context.Products.Where(m => m.CategoryId == 4).ToListAsync();
            var pizza = await _context.Products.Where(m => m.CategoryId == 5).ToListAsync();

            if (!string.IsNullOrEmpty(name))
            {
                prods = await _context.Products.Where(x => x.Name == name).ToListAsync();
            }
            var viewModel = new HomeViewModel
            {

                products = prods,
                Burger = burger,
                Chicken = chicken,
                Pizza   =   pizza,
                pagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = await _context.Products.CountAsync()
                }
            };

            return View(viewModel);
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult ShowPage(int page = 1)
        {
            return View();
        }
    }
}

Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Mhltw.Models;
using Mhltw.Repository;

namespace Mhltw.Areas.Admin.Controllers
{
    [Authorize(Roles =SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        public ProductController(IProductRepository productRepository,
       ICategoryRepository categoryRepository)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
        }
        public async Task<IActionResult> Index()
        {
            var products = await _productRepository.GetAllAsync();
            return View(products);
        }
        public async Task<IActionResult> Create()
        {
            var categories = await _categoryRepository.GetAllAsync();
            ViewBag.Categories = new SelectList(categories, "Id", "Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Product product, IFormFile imageUrl)
        {
            if (imageUrl != null)
            {
                product.ImageUrl = await SaveImage(imageUrl);
            }
            if (ModelState.IsValid)
            {
                await _productRepository.AddAsync(product);
                return RedirectToAction(nameof(Index));
            }
            var categories = await _categoryRepository.GetAllAsync();
            ViewBag.Categories = new SelectList(categories, "Id", "Name");
            return View(product);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var product = await _productRepository.GetByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            var categories = await _categoryRepository.GetAllAsync();
            ViewBag.Categories = new SelectList(categories, "Id", "Name",
            product.CategoryId);
            return View(product);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Product product, IFormFile imageUrl)
        {
            if (id != product.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                if (imageUrl != null)
                {
                    product.ImageUrl = await SaveImage(imageUrl);
                }
                await _productRepository.UpdateAsync(product);
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }
        public async Task<IActionResult> Details(int id)
        {
            var product = await _productRepository.GetByIdAsync(id);
            var category = await _categoryRepository.GetByIdAsync(product.CategoryId);
            ViewBag.Category = category.Name;
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }
        private async Task<string> SaveImage(IFormFile image)
        {
            var savePath = Path.Combine("wwwroot/image", image.FileName);
            using (var fileStream = new FileStream(savePath, FileMode.Create))
            {
                await image.CopyToAsync(fileStream);
            }
            return "/image/" + image.FileName;
        }
        public async Task<IActionResult> Delete(int id)
        {
            var product = await _productRepository.GetByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            var categories = await _categoryRepository.GetAllAsync();
            ViewBag.Categories = new SelectList(categories, "Id", "Name",
            product.CategoryId);
            return View(product);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id, Product product, IFormFile imageUrl)
        {
            if (id != product.Id)
            {
                return NotFound();
            }
            await _productRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mhltw.Extensions;
using Mhltw.Models;
using Mhltw.Repository;

namespace Mhltw.Controllers
{
	public class ShoppingCartController : Controller
	{
		private readonly IProductRepository _productRepository;
		private readonly ApplicationDbContext _context;
		private readonly UserManager<ApplicationUser> _userManager;
		public ShoppingCartController(IProductRepository productRepository, ApplicationDbContext context,
UserManager<ApplicationUser> userManager)
		{
			_productRepository = productRepository;
			_context = context;
			_userManager = userManager;
		}
        public IActionResult Checkout()
		{
			return View(new Order());
		}
		[HttpPost]
		public async Task<IActionResult> Checkout(Order order)
		{
			var cart =
			HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart");
			if (cart == null || !cart.Items.Any())
			{
				// Xử lý giỏ hàng trống...
				return RedirectToAction("Index");
			}
			var user = await _userManager.GetUserAsync(User);
			order.UserId = user.Id;
			order.OrderDate = DateTime.UtcNow;
			order.TotalPrice = cart.Items.Sum(i => i.Price * i.Quantity);
			order.OrderDetails = cart.Items.Select(i => new OrderDetail
			{
				ProductId = i.ProductId,
				Quantity = i.Quantity,
				Price = i.Price,
				ShippingAddress = order.ShippingAddress,
				Notes = order.Notes
			}).ToList();
			_context.Orders.Add(order);
			await _context.SaveChangesAsync();
			HttpContext.Session.Remove("Cart");
			return View("OrderCompleted", order.Id);
		}
		public async Task<IActionResult> AddToCart(int productId, int quantity)
		{
			// Giả sử bạn có phương thức lấy thông tin sản phẩm từ productId
			var product = await GetProductFromDatabase(productId);
			var cartItem = new CartItem
			{
				ProductId = productId,
				Name = product.Name,
				Price = product.Price,
				Quantity = quantity,
                ImageUrl = product.ImageUrl
			};
			var cart =
			HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart") ?? new
			ShoppingCart();
			cart.AddItem(cartItem);
			HttpContext.Session.SetObjectAsJson("Cart", cart);
			return RedirectToAction("Index");
		}
		public IActionResult Index()
		{
			var cart =
			HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart") ?? new
			ShoppingCart();
			return View(cart);
		}
		// Các actions khác...
		private async Task<Product> GetProductFromDatabase(int productId)
		{
			// Truy vấn cơ sở dữ liệu để lấy thông tin sản phẩm
			var product = await _productRepository.GetByIdAsync(productId);
			return product;
		}
		public IActionResult RemoveFromCart(int productId)
		{
			var cart =
			HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart");
			if (cart is not null)
			{
				cart.RemoveItem(productId);
				HttpContext.Session.SetObjectAsJson("Cart", cart);
			}

			return RedirectToAction("Index");
		}

	}
}

Views/Home/Index.cshtml
@model Mhltw.ViewModels.HomeViewModel
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
@{
    ViewData["Title"] = "Home Page";
    int numOfQuantity = 1;
}
@if (User.IsInRole("Admin"))
{
    <p>
        <a asp-action="Index" asp-controller="Product">Danh sách sản phẩm</a> | <a asp-action="IndexCategory" asp-controller="Category">Danh mục sản phẩm</a> |
    </p>
}
<div class="menu">
    <div calss="col-sm-8">
        <form id="search-form" asp-action="Index" asp-controller="Home" class="form-inline">
            <div class="search-form">
                <input class="searchbox" type="text" placeholder="Tìm kiếm..." name="Name">
                <button for="search-box" class="fas fa-search"></button>
                <button class="fa fa-refresh"> </button>
            </div>
        </form>
    </div>
</div>


<div class="panel panel-danger">
    <div class="panel-heading panel-heading-prod">Thực Đơn</div>
    <div class="panel-body">
        <div class="row">
            @foreach (var item in Model.products)
            {
                <div class="col-md-4">
                    <div class="thumbnail">
                        <img src="@Html.DisplayFor(modelItem => item.ImageUrl)" width="100px" alt="@item.Name">
                        <div class="caption">
                            <h4>@item.Name</h4>
                            <p>Giá: @string.Format("{0:N0}", item.Price) VNĐ</p>
                            <form asp-action="AddToCart" asp-controller="ShoppingCart" method="post">
                                <input type="hidden" name="productId" value="@item.Id" />
                                <p>Số Lượng:</p>
                                <input style="text-align:center" type="number" name="quantity" value="1" />
                                <button class="btn btn-success">
                                    <i class="fa fa-spin fa-spinner"></i>Add to Cart
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="panel-footer text-center">
            <ul class="pagination pagination-centered">
                @for (int i = 1; i <= Model.pagingInfo.TotalPages; i++)
                {
                    <li class="@(i == Model.pagingInfo.CurrentPage ? "active" : "")">
                        <a href="@Url.Action("Index", new { page = i })">@i</a>
                    </li>
                }
            </ul>
        </div>
    </div>
</div>

<div class="panel panel-danger">
    <div class="panel-heading panel-heading-prod">Burger</div>
    <div class="panel-body">
        <div class="row">
            @foreach (var item in Model.Burger)
            {
                <div class="col-md-4">
                    <div class="thumbnail">
                        <img src="@Html.DisplayFor(modelItem => item.ImageUrl)" width="100px" alt="@item.Name">
                        <div class="caption">
                            <h4>@item.Name</h4>
                            <p>Giá: @string.Format("{0:N0}", item.Price) VNĐ</p>
                            <form asp-action="AddToCart" asp-controller="ShoppingCart" method="post">
                                <input type="hidden" name="productId" value="@item.Id" />
                                <p>Số Lượng:</p>
                                <input style="text-align:center" type="number" name="quantity" value="1" />
                                <button class="btn btn-success">
                                    <i class="fa fa-spin fa-spinner"></i>Add to Cart
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<div class="panel panel-danger">
    <div class="panel-heading panel-heading-prod">Chiken</div>
    <div class="panel-body">
        <div class="row">
            @foreach (var item in Model.Chicken)
            {
                <div class="col-md-4">
                    <div class="thumbnail">
                        <img src="@Html.DisplayFor(modelItem => item.ImageUrl)" width="100px" alt="@item.Name">
                        <div class="caption">
                            <h4>@item.Name</h4>
                            <p>Giá: @string.Format("{0:N0}", item.Price) VNĐ</p>
                            <form asp-action="AddToCart" asp-controller="ShoppingCart" method="post">
                                <input type="hidden" name="productId" value="@item.Id" />
                                <p>Số Lượng:</p>
                                <input style="text-align:center" type="number" name="quantity" value="1" />
                                <button class="btn btn-success">
                                    <i class="fa fa-spin fa-spinner"></i>Add to Cart
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<div class="panel panel-danger">
    <div class="panel-heading panel-heading-prod">Pizza</div>
    <div class="panel-body">
        <div class="row">
            @foreach (var item in Model.Pizza)
            {
                <div class="col-md-4">
                    <div class="thumbnail">
                        <img src="@Html.DisplayFor(modelItem => item.ImageUrl)" width="100px" alt="@item.Name">
                        <div class="caption">
                            <h4>@item.Name</h4>
                            <p>Giá: @string.Format("{0:N0}", item.Price) VNĐ</p>
                            <form asp-action="AddToCart" asp-controller="ShoppingCart" method="post">
                                <input type="hidden" name="productId" value="@item.Id" />
                                <p>Số Lượng:</p>
                                <input style="text-align:center" type="number" name="quantity" value="1" />
                                <button class="btn btn-success">
                                    <i class="fa fa-spin fa-spinner"></i>Add to Cart
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        var currentUrl = window.location.pathname;
        if (currentUrl === "/") {
            currentUrl = "/trang-chu";
        }
        var navLinks = document.querySelectorAll(".navbar-nav a");
        navLinks.forEach(function (link) {
            if (link.getAttribute("href") === currentUrl) {
                link.parentNode.classList.add("active");
            }
        });
    });
</script>